name: Example test workflow for Docker using Snyk 
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk test to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: nginx 
